version: '3'

services:
    app:
        image: main-ugarit:latest
        container_name: ugarit-main-website
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        tty: true