
-- run sqlite3 ugarit_words_base.db < [command_file].sql
-- Creates a new table on the file

/*
CREATE TABLE ***TABLE_NAME*** (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL
);
*/

CREATE TABLE SEARCH_WORD (
	ID INTEGER PRIMARY KEY,
	WORD TEXT NOT NULL,
	TRANSLITERATED TEXT NOT NULL,
	CUNEIFORM TEXT NOT NULL,
	INFORMATION TEXT NOT NULL
);
