
-- UPDATE PAGES SET TITLE = 'Page not found' WHERE ID = 2

-- UPDATE PAGES SET MAINHTML = './components/pages/page_notfound.php' WHERE ID = 2;

-- UPDATE SEARCH_WORD SET TRANSLATION = 'mother' WHERE ID = 6;

--UPDATE SEARCH_WORD SET CUNEIFORM = '𐎀𐎍𐎐' WHERE ID = 10;

UPDATE SEARCH_WORD SET INFORMATION = '' WHERE ID = 18;
