

-- CHECK ALL TABLES
-- sqlite3 sql/ugarit_words_base.db "PRAGMA table_info(SEARCH);"

-- RENAME COLUMN
ALTER TABLE SEARCH_WORD RENAME COLUMN TRANSLITERATED TO TRANSLATION;

-- ADD COLUMN

ALTER TABLE NAMES ADD COLUMN ORIGIN TEXT;

-- REMOVE COLUMN

ALTER TABLE SEARCH_WORD DROP COLUMN ORIGIN;

-- ALTER TABLE TYPE

ALTER TABLE NAMES ALTER ORIGIN INTEGER;
